name: pr-validation
run-name: Lint and validate C code
on:
    pull_request:
        types: [opened]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: sudo apt-get install -y gcc make
        - run: |
            make
            gcc -Wall -Wextra -pedantic -std=c99 -fsanitize=undefined -fsanitize=address -o main main.c
            ./main
