name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                arch: [amd64]
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install -y gcc make
            - run: make
            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: |
                  Changes in this release:
                  - Add feature A
                  - Fix bug B
                draft: false
                prerelease: false
            - name: Upload assets
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./awc
              asset_name: awc-${{ matrix.os }}-${{ matrix.arch }}
              asset_content_type: application/octet-stream
